# Generated by Django 4.0.6 on 2023-02-21 18:05

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('sur_name', models.CharField(blank=True, max_length=150, null=True)),
                ('other_name', models.CharField(blank=True, max_length=150, null=True)),
                ('username', models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone_no', models.CharField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_landlord', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LandLordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('national_id_number', models.PositiveIntegerField(unique=True)),
                ('national_id_image', models.ImageField(upload_to='doucments/IDs/')),
                ('profile_photo', models.ImageField(upload_to='doucments/profilePhotos/')),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landLord', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandLordPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('9mobile 9Payment Service Bank', '9mobile 9Payment Service Bank'), ('Abbey Mortgage Bank', 'Abbey Mortgage Bank'), ('Above Only MFB', 'Above Only MFB'), ('Abulesoro MFB', 'Abulesoro MFB'), ('Access Bank', 'Access Bank'), ('Access Bank (Diamond)', 'Access Bank (Diamond)'), ('Accion Microfinance Bank', 'Accion Microfinance Bank'), ('Ahmadu Bello University Microfinance Bank', 'Ahmadu Bello University Microfinance Bank'), ('Airtel Smartcash PSB', 'Airtel Smartcash PSB'), ('ALAT by WEMA', 'ALAT by WEMA'), ('Amju Unique MFB', 'Amju Unique MFB'), ('Aramoko MFB', 'Aramoko MFB'), ('ASO Savings and Loans', 'ASO Savings and Loans'), ('Astrapolaris MFB LTD', 'Astrapolaris MFB LTD'), ('Bainescredit MFB', 'Bainescredit MFB'), ('Bowen Microfinance Bank', 'Bowen Microfinance Bank'), ('Carbon', 'Carbon'), ('CEMCS Microfinance Bank', 'CEMCS Microfinance Bank'), ('Chanelle Microfinance Bank Limited', 'Chanelle Microfinance Bank Limited'), ('Citibank Nigeria', 'Citibank Nigeria'), ('Corestep MFB', 'Corestep MFB'), ('Coronation Merchant Bank', 'Coronation Merchant Bank'), ('Crescent MFB', 'Crescent MFB'), ('Dot Microfinance Bank', 'Dot Microfinance Bank'), ('Ecobank Nigeria', 'Ecobank Nigeria'), ('Ekimogun MFB', 'Ekimogun MFB'), ('Ekondo Microfinance Bank', 'Ekondo Microfinance Bank'), ('Eyowo', 'Eyowo'), ('Fairmoney Microfinance Bank', 'Fairmoney Microfinance Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Firmus MFB', 'Firmus MFB'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('First City Monument Bank', 'First City Monument Bank'), ('FSDH Merchant Bank Limited', 'FSDH Merchant Bank Limited'), ('Gateway Mortgage Bank LTD', 'Gateway Mortgage Bank LTD'), ('Globus Bank', 'Globus Bank'), ('GoMoney', 'GoMoney'), ('Goodnews Microfinance Bank', 'Goodnews Microfinance Bank'), ('Greenwich Merchant Bank', 'Greenwich Merchant Bank'), ('Guaranty Trust Bank', 'Guaranty Trust Bank'), ('Hackman Microfinance Bank', 'Hackman Microfinance Bank'), ('Hasal Microfinance Bank', 'Hasal Microfinance Bank'), ('Heritage Bank', 'Heritage Bank'), ('HopePSB', 'HopePSB'), ('Ibile Microfinance Bank', 'Ibile Microfinance Bank'), ('Ikoyi Osun MFB', 'Ikoyi Osun MFB'), ('Ilaro Poly Microfinance Bank', 'Ilaro Poly Microfinance Bank'), ('Infinity MFB', 'Infinity MFB'), ('Jaiz Bank', 'Jaiz Bank'), ('Kadpoly MFB', 'Kadpoly MFB'), ('Keystone Bank', 'Keystone Bank'), ('Kredi Money MFB LTD', 'Kredi Money MFB LTD'), ('Kuda Bank', 'Kuda Bank'), ('Lagos Building Investment Company Plc.', 'Lagos Building Investment Company Plc.'), ('Links MFB', 'Links MFB'), ('Living Trust Mortgage Bank', 'Living Trust Mortgage Bank'), ('Lotus Bank', 'Lotus Bank'), ('Mayfair MFB', 'Mayfair MFB'), ('Mint MFB', 'Mint MFB'), ('MTN Momo PSB', 'MTN Momo PSB'), ('Paga', 'Paga'), ('PalmPay', 'PalmPay'), ('Parallex Bank', 'Parallex Bank'), ('Parkway - ReadyCash', 'Parkway - ReadyCash'), ('Paycom', 'Paycom'), ('Petra Mircofinance Bank Plc', 'Petra Mircofinance Bank Plc'), ('Polaris Bank', 'Polaris Bank'), ('Polyunwana MFB', 'Polyunwana MFB'), ('PremiumTrust Bank', 'PremiumTrust Bank'), ('Providus Bank', 'Providus Bank'), ('QuickFund MFB', 'QuickFund MFB'), ('Rand Merchant Bank', 'Rand Merchant Bank'), ('Refuge Mortgage Bank', 'Refuge Mortgage Bank'), ('ROCKSHIELD MICROFINANCE BANK', 'ROCKSHIELD MICROFINANCE BANK'), ('Rubies MFB', 'Rubies MFB'), ('Safe Haven MFB', 'Safe Haven MFB'), ('Safe Haven Microfinance Bank Limited', 'Safe Haven Microfinance Bank Limited'), ('Shield MFB', 'Shield MFB'), ('Solid Rock MFB', 'Solid Rock MFB'), ('Sparkle Microfinance Bank', 'Sparkle Microfinance Bank'), ('Stanbic IBTC Bank', 'Stanbic IBTC Bank'), ('Standard Chartered Bank', 'Standard Chartered Bank'), ('Stellas MFB', 'Stellas MFB'), ('Sterling Bank', 'Sterling Bank'), ('Suntrust Bank', 'Suntrust Bank'), ('Supreme MFB', 'Supreme MFB'), ('TAJ Bank', 'TAJ Bank'), ('Tanadi Microfinance Bank', 'Tanadi Microfinance Bank'), ('Tangerine Money', 'Tangerine Money'), ('TCF MFB', 'TCF MFB'), ('Titan Bank', 'Titan Bank'), ('Titan Paystack', 'Titan Paystack'), ('Uhuru MFB', 'Uhuru MFB'), ('Unaab Microfinance Bank Limited', 'Unaab Microfinance Bank Limited'), ('Unical MFB', 'Unical MFB'), ('Unilag Microfinance Bank', 'Unilag Microfinance Bank'), ('Union Bank of Nigeria', 'Union Bank of Nigeria'), ('United Bank For Africa', 'United Bank For Africa'), ('Unity Bank', 'Unity Bank'), ('VFD Microfinance Bank Limited', 'VFD Microfinance Bank Limited'), ('Wema Bank', 'Wema Bank'), ('Zenith Bank', 'Zenith Bank')], default='Access Bank', max_length=100, verbose_name='Bank Name')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.PositiveIntegerField()),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentdetail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
