# Generated by Django 4.0.6 on 2023-02-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_landlordprofile_recommended_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
