# Generated by Django 4.0.6 on 2023-01-31 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[('ground-floor', 'Ground Floor'), ('first-floor', 'First Floor'), ('second-floor', 'Second Floor'), ('third-floor', 'Third Floor'), ('fourth-floor', 'Fourth Floor'), ('fifth-floor', 'Fifth Floor'), ('sixth-floor', 'Sixth Floor'), ('seven-floor', 'Seventh Floor')], max_length=50)),
                ('side', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], max_length=50)),
                ('taken', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('accommodation_type', models.CharField(choices=[('self_con', 'Self Contain'), ('a room_parlor', 'A Room And Parlor'), ('2-rooms-flat', '2 BedRooms Flat'), ('3-rooms-flat', '3 BedRooms Flat'), ('1-room', '1 Room'), ('shop', 'Shop'), ('hall', 'Hall'), ('mall', 'Mall'), ('warehouse', 'Warehouse')], max_length=50, verbose_name='Accommodation Type')),
                ('bedroom', models.ImageField(upload_to='BuildingInterior/bedroom')),
                ('kitchen', models.ImageField(upload_to='BuildingInterior/kitchen')),
                ('sittingroom', models.ImageField(upload_to='BuildingInterior/livingroom')),
                ('convience', models.ImageField(upload_to='BuildingInterior/convience')),
            ],
        ),
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Building Name')),
                ('address', models.CharField(max_length=150, verbose_name='Building Address')),
                ('building_type', models.CharField(choices=[('Bungalow', 'Bungalow'), ('duplex', 'Duplex'), ('1-story', '1 Story Building'), ('2-story-building', '2 Story Building'), ('3-story-building', '3 Story Building'), ('4-story-building', '4 Story Building'), ('5-story-building', '5 Story Building'), ('6-story-building', '6 Story Building'), ('2-story-building-plaza', '2 Story Building Plaza'), ('3-story-building-plaza', '3 Story Building Plaza'), ('4-story-building-plaza', '4 Story Building Plaza'), ('5-story-building-plaza', '5 Story Building Plaza'), ('6-story-building-plaza', '6 Story Building Plaza')], max_length=50, verbose_name='Building Type')),
                ('accommodation_type', models.CharField(choices=[('self_con', 'Self Contain'), ('a room_parlor', 'A Room And Parlor'), ('2-rooms-flat', '2 BedRooms Flat'), ('3-rooms-flat', '3 BedRooms Flat'), ('1-room', '1 Room'), ('shop', 'Shop'), ('hall', 'Hall'), ('mall', 'Mall'), ('warehouse', 'Warehouse')], max_length=50, verbose_name='Accommodation Type')),
                ('total_number_of_accommodation_space', models.PositiveIntegerField(verbose_name='Total Number Of Accodation Space')),
                ('available_number_accommodation_space', models.PositiveIntegerField(verbose_name='Number Of Accodation Space Available')),
                ('house_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Building Price')),
                ('electricity', models.BooleanField(default=True)),
                ('water', models.BooleanField(default=False)),
                ('newly_built', models.BooleanField(default=False, verbose_name='Newly Built')),
                ('sale', models.BooleanField(default=False, verbose_name='For Sale')),
                ('exterior_image', models.ImageField(blank=True, null=True, upload_to='BuildingExterior/', verbose_name='Exterior Image')),
                ('c_of_o', models.FileField(blank=True, null=True, upload_to='doucments/CofOs/', verbose_name='Certificate Of Occupancy')),
                ('d_of_a', models.FileField(blank=True, null=True, upload_to='doucments/DofAs/', verbose_name='Deed Of Assignment')),
                ('tenant_agreement', models.FileField(blank=True, null=True, upload_to='doucments/TAs/', verbose_name='Tenant Agreement')),
                ('verified', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.subregion')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.country')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[('ground-floor', 'Ground Floor'), ('first-floor', 'First Floor'), ('second-floor', 'Second Floor'), ('third-floor', 'Third Floor'), ('fourth-floor', 'Fourth Floor'), ('fifth-floor', 'Fifth Floor'), ('sixth-floor', 'Sixth Floor'), ('seven-floor', 'Seventh Floor')], max_length=50)),
                ('spacename', models.CharField(max_length=50)),
                ('taken', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('accommodation_type', models.CharField(choices=[('self_con', 'Self Contain'), ('a room_parlor', 'A Room And Parlor'), ('2-rooms-flat', '2 BedRooms Flat'), ('3-rooms-flat', '3 BedRooms Flat'), ('1-room', '1 Room'), ('shop', 'Shop'), ('hall', 'Hall'), ('mall', 'Mall'), ('warehouse', 'Warehouse')], max_length=50, verbose_name='Accommodation Type')),
                ('image', models.ImageField(upload_to='BuildingInterior/space')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.housemodel')),
            ],
        ),
    ]
