# Generated by Django 4.0.6 on 2023-02-21 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenitiesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('First Floor', 'First Floor'), ('Second Floor', 'Second Floor'), ('Third Floor', 'Third Floor'), ('Fourth Floor', 'Fourth Floor'), ('Fifth Floor', 'Fifth Floor'), ('Sixth Floor', 'Sixth Floor'), ('Seventh Floor', 'Seventh Floor')], max_length=50)),
                ('side', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], max_length=50)),
                ('taken', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('accommodation_type', models.CharField(choices=[('1 Room', '1 Room'), ('Self Contain', 'Self Contain'), ('A Room And Parlor', 'A Room And Parlor'), ('2 Bedrooms', '2 BedRooms'), ('3 Bedrooms', '3 BedRooms'), ('4 Bedrooms', '4 BedRooms'), ('5 Bedrooms', '5 BedRooms'), ('6 Bedrooms', '6 BedRooms'), ('Shop', 'Shop'), ('Office', 'Office'), ('Hall', 'Hall'), ('Mall', 'Mall'), ('Warehouse', 'Warehouse')], max_length=50, verbose_name='Accommodation Type')),
                ('description', models.TextField(blank=True, max_length=600, null=True, verbose_name='Description')),
                ('bedroom', models.ImageField(upload_to='BuildingInterior/bedroom')),
                ('bedroom_master', models.ImageField(upload_to='BuildingInterior/bedroom')),
                ('kitchen', models.ImageField(upload_to='BuildingInterior/kitchen')),
                ('sittingroom', models.ImageField(upload_to='BuildingInterior/livingroom')),
                ('convience', models.ImageField(upload_to='BuildingInterior/convience')),
                ('vid_file', models.FileField(upload_to='BuildingInterior/video/flat')),
            ],
        ),
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Building Name')),
                ('address', models.CharField(max_length=150, verbose_name='Building Address')),
                ('building_type', models.CharField(choices=[('Bungalow', 'Bungalow'), ('Duplex', 'Duplex'), ('1 Story Building Apartment', '1 Story Building Apartment'), ('2 Story Building Apartment', '2 Story Building Apartment'), ('2 Story Building Apartment', '3 Story Building Apartment'), ('2 Story Building Apartment', '4 Story Building Apartment'), ('5 Story Building Apartment', '5 Story Building Apartment'), ('6 Story Building Apartment', '6 Story Building Apartment'), ('2 Story Building Plaza', '2 Story Building Plaza'), ('3 Story Building Plaza', '3 Story Building Plaza'), ('4 Story Building Plaza', '4 Story Building Plaza'), ('5 Story Building Plaza', '5 Story Building Plaza'), ('6 Story Building Plaza', '6 Story Building Plaza')], max_length=50, verbose_name='Building Type')),
                ('accommodation_type', models.CharField(choices=[('1 Room', '1 Room'), ('Self Contain', 'Self Contain'), ('A Room And Parlor', 'A Room And Parlor'), ('2 Bedrooms', '2 BedRooms'), ('3 Bedrooms', '3 BedRooms'), ('4 Bedrooms', '4 BedRooms'), ('5 Bedrooms', '5 BedRooms'), ('6 Bedrooms', '6 BedRooms'), ('Shop', 'Shop'), ('Office', 'Office'), ('Hall', 'Hall'), ('Mall', 'Mall'), ('Warehouse', 'Warehouse')], max_length=50, verbose_name='Accommodation Type')),
                ('total_number_of_accommodation_space', models.PositiveIntegerField(verbose_name='Total Number Of Accodation Space')),
                ('available_number_accommodation_space', models.PositiveIntegerField(verbose_name='Number Of Accodation Space Available')),
                ('house_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Building Price')),
                ('electricity', models.BooleanField(default=True)),
                ('water', models.BooleanField(default=False)),
                ('newly_built', models.BooleanField(default=False, verbose_name='Newly Built')),
                ('sale', models.BooleanField(default=False, verbose_name='For Sale')),
                ('exterior_image', models.ImageField(blank=True, null=True, upload_to='BuildingExterior/', verbose_name='Exterior Image Main')),
                ('exterior_image_side1', models.ImageField(blank=True, null=True, upload_to='BuildingExterior/', verbose_name='Exterior Image Side')),
                ('exterior_image_side2', models.ImageField(blank=True, null=True, upload_to='BuildingExterior/', verbose_name='Exterior Image Side')),
                ('vid_file', models.FileField(blank=True, null=True, upload_to='BuildingInterior/video/building/')),
                ('c_of_o', models.FileField(blank=True, null=True, upload_to='doucments/CofOs/', verbose_name='Certificate Of Occupancy')),
                ('d_of_a', models.FileField(blank=True, null=True, upload_to='doucments/DofAs/', verbose_name='Deed Of Assignment')),
                ('tenant_agreement', models.FileField(blank=True, null=True, upload_to='doucments/TAs/', verbose_name='Tenant Agreement')),
                ('verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.subregion')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.country')),
                ('features', models.ManyToManyField(to='houses.amenitiesmodels')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('First Floor', 'First Floor'), ('Second Floor', 'Second Floor'), ('Third Floor', 'Third Floor'), ('Fourth Floor', 'Fourth Floor'), ('Fifth Floor', 'Fifth Floor'), ('Sixth Floor', 'Sixth Floor'), ('Seventh Floor', 'Seventh Floor')], max_length=50)),
                ('side', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], max_length=50)),
                ('spacename', models.CharField(max_length=50)),
                ('taken', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('accommodation_type', models.CharField(blank=True, choices=[('1 Room', '1 Room'), ('Self Contain', 'Self Contain'), ('A Room And Parlor', 'A Room And Parlor'), ('2 Bedrooms', '2 BedRooms'), ('3 Bedrooms', '3 BedRooms'), ('4 Bedrooms', '4 BedRooms'), ('5 Bedrooms', '5 BedRooms'), ('6 Bedrooms', '6 BedRooms'), ('Shop', 'Shop'), ('Office', 'Office'), ('Hall', 'Hall'), ('Mall', 'Mall'), ('Warehouse', 'Warehouse')], max_length=50, null=True, verbose_name='Accommodation Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='BuildingInterior/space')),
                ('features', models.ManyToManyField(to='houses.amenitiesmodels')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space', to='houses.housemodel')),
            ],
        ),
    ]
