# Generated by Django 4.0.6 on 2023-01-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacemodel',
            name='accommodation_type',
        ),
        migrations.RemoveField(
            model_name='spacemodel',
            name='image',
        ),
    ]
