# Generated by Django 4.0.6 on 2023-01-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_spacemodel_accommodation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacemodel',
            name='accommodation_type',
            field=models.CharField(blank=True, choices=[('self_con', 'Self Contain'), ('a room_parlor', 'A Room And Parlor'), ('2-rooms-flat', '2 BedRooms Flat'), ('3-rooms-flat', '3 BedRooms Flat'), ('1-room', '1 Room'), ('shop', 'Shop'), ('hall', 'Hall'), ('mall', 'Mall'), ('warehouse', 'Warehouse')], max_length=50, null=True, verbose_name='Accommodation Type'),
        ),
        migrations.AddField(
            model_name='spacemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='BuildingInterior/space'),
        ),
    ]
