# Generated by Django 4.0.6 on 2023-02-14 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_spacemodel_accommodation_type_spacemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatmodel',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='houses.housemodel'),
        ),
    ]
