# Generated by Django 4.0.6 on 2023-02-14 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_flatmodel_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacemodel',
            name='side',
            field=models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='right', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flatmodel',
            name='accommodation_type',
            field=models.CharField(choices=[('1-room', '1 Room'), ('self_con', 'Self Contain'), ('a room_parlor', 'A Room And Parlor'), ('2-rooms-flat', '2 BedRooms'), ('3-rooms-flat', '3 BedRooms'), ('4-rooms-flat', '4 BedRooms'), ('5-rooms-flat', '5 BedRooms'), ('6-rooms-flat', '6 BedRooms'), ('shop', 'Shop'), ('office', 'Office'), ('hall', 'Hall'), ('mall', 'Mall'), ('warehouse', 'Warehouse')], max_length=50, verbose_name='Accommodation Type'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='accommodation_type',
            field=models.CharField(choices=[('1-room', '1 Room'), ('self_con', 'Self Contain'), ('a room_parlor', 'A Room And Parlor'), ('2-rooms-flat', '2 BedRooms'), ('3-rooms-flat', '3 BedRooms'), ('4-rooms-flat', '4 BedRooms'), ('5-rooms-flat', '5 BedRooms'), ('6-rooms-flat', '6 BedRooms'), ('shop', 'Shop'), ('office', 'Office'), ('hall', 'Hall'), ('mall', 'Mall'), ('warehouse', 'Warehouse')], max_length=50, verbose_name='Accommodation Type'),
        ),
        migrations.AlterField(
            model_name='spacemodel',
            name='accommodation_type',
            field=models.CharField(blank=True, choices=[('1-room', '1 Room'), ('self_con', 'Self Contain'), ('a room_parlor', 'A Room And Parlor'), ('2-rooms-flat', '2 BedRooms'), ('3-rooms-flat', '3 BedRooms'), ('4-rooms-flat', '4 BedRooms'), ('5-rooms-flat', '5 BedRooms'), ('6-rooms-flat', '6 BedRooms'), ('shop', 'Shop'), ('office', 'Office'), ('hall', 'Hall'), ('mall', 'Mall'), ('warehouse', 'Warehouse')], max_length=50, null=True, verbose_name='Accommodation Type'),
        ),
        migrations.AlterField(
            model_name='spacemodel',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space', to='houses.housemodel'),
        ),
    ]
