# Generated by Django 4.0.6 on 2023-02-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_flatmodel_features_and_more'),
        ('payment_manager', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='space_paidfor',
            new_name='apartment_paidfor',
        ),
        migrations.AddField(
            model_name='payment',
            name='others_paidfor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='houses.spacemodel'),
        ),
    ]
