# Generated by Django 4.0.6 on 2023-03-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_manager', '0003_rename_space_paidfor_payment_apartment_paidfor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='others_paidfor',
            new_name='space_paidfor',
        ),
    ]
